[[main]]
  name = "Posts"
  url = "/posts/"
  weight = 10

[[main]]
  name = "About"
  url = "/about/"
  weight = 20

[[footer]]
  name = "Posts"
  url = "/posts/"
  weight = 10

[[footer]]
  name = "About"
  url = "/about/"
  weight = 20
